//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Pre_Engineering.AIEEE {
    
    
    public partial class AIEEE_test_centers_exam_cities {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.AIEEELinks1 Master {
            get {
                return ((ExamCrazy.Masters.AIEEELinks1)(base.Master));
            }
        }
    }
}
