//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Engineering.Computer_Science {
    
    
    public partial class Data_Structures_and_Algorithms_Running_Time {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.DSOLinks Master {
            get {
                return ((ExamCrazy.Masters.DSOLinks)(base.Master));
            }
        }
    }
}
