//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Engineering.Electrical {
    
    
    public partial class Shunt_DC_Motors_Principle_Speed_Control_Installation_Applications {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.ElectricalLinks Master {
            get {
                return ((ExamCrazy.Masters.ElectricalLinks)(base.Master));
            }
        }
    }
}
