//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Engineering.Computer_Science.Computer_Organization_and_Architecture {
    
    
    public partial class The_Page_Table {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.Memory_System_Links Master {
            get {
                return ((ExamCrazy.Masters.Memory_System_Links)(base.Master));
            }
        }
    }
}
