//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Engineering.Mechanical {
    
    
    public partial class Tutorial_on_Helical_Springs_Surge_and_critical_frequency {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.MechanicalLinks Master {
            get {
                return ((ExamCrazy.Masters.MechanicalLinks)(base.Master));
            }
        }
    }
}
