<%@ Page Language="C#" MasterPageFile="~/Masters/gaillinks.master" AutoEventWireup="True" CodeBehind="GAIL-JOBS-How-to-apply.aspx.cs"  Inherits="ExamCrazy.Interviews_Jobs.Government_Jobs.GAIL_JOBS_How_to_apply" %>
<%@ MasterType VirtualPath="~/Masters/gaillinks.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToBreadCrum" runat="server"></asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">
<div class="gbody txt">

 

<table border="0" width="99%" cellspacing=2 cellpadding=2 bordercolor='#e4e4e4'>

    <tr>

      
      <td class="txt">
	<b>GAIL - How to Apply </b></td>
</tr>

    <tr>

      
      <td class="txt">
<br>1) <b><i>CANDIDATES WILL BE REQUIRED TO APPLY ONLINE THROUGH WEBSITE: www.gailonline.com.</b></i> No other means / mode of application shall be accepted. Website will be open from 1000 hrs on 21.05.2009 to 1700 hrs on 15.06.2009. 
<br>2) A Candidate can apply for one post only. Candidates applying for more than one post will not be considered. 
<br>3) Candidates belonging to General and OBC category are required to pay a non- refundable application fees of Rs. 200/- (Rupees two hundred only) by demand draft drawn in favour of GAIL (India) Limted payable at State Bank of India, Bhikaiji Cama Place (Branch Code: 7755), New Delhi . SC/ST/PH candidates are exempted from payment of above fees provided they attach an attested copy of SC /ST /PH certificate as applicable, issued by the Competent Authority. After applying online, candidate is required to download the registration slip generated by the system in duplicate with unique registration number place for photograph and signature and other details. The candidate has to send one print out of the registration slip duly signed and affixing latest passport size colored photograph along with required demand draft. The registration number, name, discipline and category should be written at the back of the demand draft. SC/ST/PH candidates are required to attach an attested copy of SC/ST/PH certificate from the competent authority along with one print out of the registration slip duly signed and affixing latest passport size colored photograph. Registration slip should not have any enclosure except the Demand draft and SC/ST/PH certificate as applicable. In case of any overwriting or tampering of registration slip, the candidature of the concerned candidates shall be rejected. The Envelope containing above details should be superscribed with "APPLICATION FOR THE POST OF EXECUTIVE TRAINEE-2009” (DISCIPLINE, REGN. NO. and CATEGORY: GEN/SC/ST/OBC/PH/EXSER as the case may be) and should be sent by ordinary post to PO Box No. 1102, 3rd Block, Jayanagar Post Office, Bangalore – 560 011 latest by 25.06.2009. GAIL will not be responsible for postal delay or loss / non-delivery thereof. General and OBC candidates should have their Demand Draft ready while applying online, as the DD details would also be required to be entered in the online application. Without the DD details data will not be registered. 
<br>
<br><b>Other Information</b>
<br>
<br>1. Request for change of Mailing address, examination centre / category/ discipline as declared in the online application will not be entertained. Candidates are required to give two choices in respect to the Test Centres in the online application form. The choices given by the candidates in respect of the Test Centre for written test shall only be considered as their preferred choice. Actual Test Centre will be allotted by GAIL and the same shall be considered final. Any changes in the preferences already indicated by the candidate shall not be allowed by GAIL nor any correspondence in this regard will be entertained under any circumstances. GAIL also reserves the right to cancel or add any centre for written test depending upon the response in that area / centre. 
<br>
<br>2. Candidates should possess a valid email ID. Candidates are advised to keep the email ID (to be entered compulsorily in the online application form) active for at least one year. No change in the email ID will be allowed once entered. All correspondence with candidates shall be done through Email only. All information regarding Examination schedule / test centre / admit card / guidelines / interview call letters etc. shall be provided through E-mail to the candidates found apparently eligible based on the online application data. Responsibilities of receiving, downloading and printing of admit card etc. will be of the candidate. GAIL will not be responsible for any loss of E-mail sent, due to invalid / wrong E-mail ID provided by the candidate. 
<br>
<br>3. Only short listed candidates who are found apparently eligible based on the online application data will be called for written test and / or interview as the case may be. In case the applicant does not receive any communication within 90 days from the date of publication of this advertisement, it may be presumed that he/she has not been short listed for test and / or interview. 
<br>4. Category (SC/ST/OBC/PH) once filled in the online application form will not be changed and no benefit of other category will be admissible later on. 
<br>
<br>5. The OBC candidates who belong to "CREAMY LAYER” are not entitled for OBC concession and such candidates have to indicate their category as "General”. 
<br>
<br>6. Relaxations / Reservations for SC/ST/OBC(Non Creamy Layer)/PH as per Government Directives are applicable. 
<br>
<br>7. For claiming the benefit of Physically Handicapped, the candidates should produce Medical Certificate issued by a Medical Board attached to the Special Employment Exchange / Vocational Rehabilitation Centre for PH or Head of concerned Department of a Government Civil Hospital satisfying the prescribed disability criteria. Candidates are required to submit the certificate in the prescribed format in support of their claim. Prescribed formats are hosted at IMPORTANT INSTRUCTIONS BEFORE YOU APPLY ONLINE. In case, the candidate fails to produce the certificate in the prescribed format issued by Competent Authority, his / her candidature will not be considered. 
<br>
<br>8. Candidates from SC/ST/OBC category should produce their caste certificate issued by Competent Authority in the prescribed format in support of their claim. Prescribed formats are hosted at IMPORTANT INSTRUCTIONS BEFORE YOU APPLY ONLINE. In case, the candidate fails to produce the certificate in the prescribed format issued by Competent Authority, his / her candidature will not be considered. 
<br>
<br>9. The Candidates employed in Govt. Department / PSU / Autonomous bodies must produce NOC at the time of Interview. In case, the candidate fails to produce the certificate his / her candidature will not be considered. 
<br>
<br>10. Candidature of the registered candidate is liable to be rejected at any stage of the recruitment process or after recruitment or joining, if any information provided by the candidate is found to be false or is not found inconformity with eligibility criteria mentioned in the advertisement. 
<br>
<br>11. Candidature of the registered candidate is also liable to be rejected if valid registration slip along with necessary documents is not received or received unsigned or without affixing passport size colored photograph or without application fees or received after the closing date or registered online more than once. 12. GAIL reserves the right to raise the minimum eligibility standards and / or relax age, experience criteria in otherwise suitable cases. The Management reserves the right to fill or not to fill all or any of the above positions without assigning any reason whatsoever. 
<br>
<br>13. The prescribed qualification / experience are the minimum and mere possession of the same does not entitle a candidate for written test / interview. GAIL's decision shall be final in this regard. 
<br>
<br>14. Any canvassing directly or indirectly by the applicant will disqualify his/her candidature. Any dispute with regard to recruitment against this advertisement will be settled within the jurisdiction of Delhi Court only 
</td>
</tr></table>
<br>
<br>
<br>
	<br>Top of Form<Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
	<br>Sir i am final year student of B Tech (Petroleum) is there any scope or oppertunative for us to join GAIL ? if any thing possible pl guide us </td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>Krupeshsinh. &nbsp;&nbsp;&nbsp; <b>On:</b> Dec 24, 2011 - 1:12:14 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink1" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink2" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('4506','Sir%20i%20am%20final%20year%20student%20of%20B%20Tech%20(Petroleum)%20is%20there%20any%20scope%20or%20oppertunative%20for%20us%20to%20join%20GAIL%20?%20if%20%20any%20thing%20possible%20pl%20guide%20us%20') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink3" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('1','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>Sir i am final year student of B Tech (Petroleum) is there any scope for us to join our eligible for any exem conducted by GAIL? is there any near by oppertunative pl inform us Regards 
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>Krupeshsinh. &nbsp;&nbsp;&nbsp; <b>On:</b> Dec 24, 2011 - 1:07:39 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink4" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink5" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('4505','Sir%20i%20am%20final%20year%20student%20of%20B%20Tech%20(Petroleum)%20is%20there%20any%20scope%20for%20us%20to%20join%20our%20eligible%20for%20any%20%20exem%20conducted%20by%20GAIL?%20is%20there%20any%20near%20by%20oppertunative%20pl%20inform%20us%20%20Regards%20') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink6" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('2','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>sir i want the syllabus for instrumentation branch
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>vaishali paunikar. &nbsp;&nbsp;&nbsp; <b>On:</b> Oct 18, 2011 - 2:17:10 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink7" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink8" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('4199','sir%20i%20want%20the%20syllabus%20for%20instrumentation%20branch') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink9" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('3','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>sir,how can i download my admit card
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>k.karthik. &nbsp;&nbsp;&nbsp; <b>On:</b> Oct 17, 2011 - 6:35:45 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink10" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink11" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('4195','sir,how%20can%20i%20download%20my%20admit%20card') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink12" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('4','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>I am doing mechanical engineering 7th semester Am I eligible? please reply 
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>harikrishnan. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 19, 2011 - 9:08:43 AM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink13" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink14" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('4047','I%20am%20%20doing%20mechanical%20engineering%207th%20semester%20%20Am%20I%20eligible?%20please%20reply%20') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink15" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('5','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>Sir,can a 4th year appearing student apply for the gail exam?
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>kousik. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 10, 2011 - 10:50:06 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink16" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink17" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3972','Sir,can%20a%204th%20year%20appearing%20student%20apply%20for%20the%20gail%20exam?') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink18" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('6','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>Sir i am doing 4th b tech can i eligible for this job my course is electrical and electronics engineering 
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>deepak kumar. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 9, 2011 - 6:45:30 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink19" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink20" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3964','Sir%20i%20am%20doing%204th%20b%20tech%20can%20i%20eligible%20for%20this%20job%20my%20course%20is%20electrical%20and%20electronics%20engineering%20') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink21" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('7','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>sir please tell me wthether i have to send the dd(damand draft) along with application form
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>kannu. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 9, 2011 - 10:20:31 AM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink22" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink23" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3953','sir%20please%20tell%20me%20wthether%20i%20have%20to%20send%20the%20dd(damand%20draft)%20along%20with%20application%20form') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink24" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('8','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>sir please tell me wthether i have to send the dd(damand draft) along with application form?
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>kanika. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 9, 2011 - 10:17:07 AM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink25" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink26" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3952','sir%20please%20tell%20me%20wthether%20i%20have%20to%20send%20the%20dd(damand%20draft)%20along%20with%20application%20form?') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink27" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('9','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>can final year students can apply? 
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>bhavani. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 8, 2011 - 8:39:07 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink28" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink29" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3948','can%20final%20year%20students%20can%20apply?') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink30" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('10','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>can final year students can apply? 
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>bhavani. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 8, 2011 - 8:11:19 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink31" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink32" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3947','can%20final%20year%20students%20can%20apply?') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink33" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('11','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>sir,can 4th year students can also apply?ece deapartment
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>bhavani. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 8, 2011 - 8:10:40 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink34" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink35" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3946','sir,can%204th%20year%20students%20can%20also%20apply?ece%20deapartment') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink36" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('12','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>i m doing 6 sem in electronics and communication i m eligible for this job or not 
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>pavan kumar. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 8, 2011 - 1:08:05 AM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink37" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink38" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3932','i%20m%20doing%206%20sem%20in%20electronics%20and%20communication%20i%20m%20eligible%20for%20this%20job%20or%20not%20') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink39" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('13','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>good evening sir as i have completed my B E in chemical engineering and got first class with one back log so may i eligible for the prescribed job
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>megha. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 6, 2011 - 7:20:58 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink40" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink41" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3921','good%20evening%20sir%20%20as%20i%20have%20completed%20my%20B%20E%20%20in%20chemical%20engineering%20and%20got%20first%20class%20with%20one%20back%20log%20so%20may%20i%20eligible%20for%20the%20prescribed%20job') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink42" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('14','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>Sir iam doing 4th b tech can i eligible for this job my course is electrical and electronics engineering
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Posted by:-</b>Shaik sulthan. &nbsp;&nbsp;&nbsp; <b>On:</b> Sep 6, 2011 - 5:50:40 PM 
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><asp:HyperLink ID="HyperLink43" runat="server" Text="Bookmark or Email" NavigateUrl="http://www.addthis.com/bookmark.php"></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink44" runat="server" Text="Report Abuse" NavigateUrl="javascript:reportAbuse('3919','Sir%20iam%20doing%204th%20b%20tech%20%20can%20i%20eligible%20for%20this%20job%20%20%20%20my%20course%20is%20electrical%20and%20electronics%20engineering') "></asp:HyperLink> </td>

      
      <td class="txt">
	<br><asp:HyperLink ID="HyperLink45" runat="server" Text="Post your comment" NavigateUrl="javascript:showDiv('15','15') "></asp:HyperLink> </td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><b>&nbsp;</b><b>Enter your reply here</b>
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Post your Comments on this topic </b>
</td>
</tr>

    <tr>

      
      <td class="txt"><Table border="1" cellspacing="2" cellpadding="2" bordercolor="#c4c4c4">

    <tr>

      
      <td class="txt">
<br><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image1.wmf"></sub></td>
</tr>

    <tr>

      
      <td class="txt">
<br><b>Name:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image2.wmf"></sub> &nbsp; <b>Email:</b><sub><img src="/Interviews-Jobs/Government-Jobs/img_gail-jobs-how-to-apply/image3.wmf"></sub> 
</td>
</tr></table>
<br>
</td>
</tr>

    <tr>

      
      <td class="txt">
<br>View more comments <asp:HyperLink ID="HyperLink46" runat="server" Text="&nbsp;&nbsp;<b>1</b>" NavigateUrl="~/interviews-jobs/government-jobs/gail-jobs-how-to-apply.aspx"></asp:HyperLink> <asp:HyperLink ID="HyperLink47" runat="server" Text="&nbsp;&nbsp;<b>2</b>" NavigateUrl="~/interviews-jobs/government-jobs/gail-jobs-how-to-apply.aspx"></asp:HyperLink> 
</td>
</tr></table>
<br>Bottom of Form
	</div>
</asp:Content>
