//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Interviews_Jobs.Government_Jobs {
    
    
    public partial class Government_Jobs {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.Government_Jobs_Links Master {
            get {
                return ((ExamCrazy.Masters.Government_Jobs_Links)(base.Master));
            }
        }
    }
}
