//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Pre_Engineering {
    
    
    public partial class Admission_notifications_Engineering_institutes_india_BE_Btech {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.Engineering_Bachelor_links Master {
            get {
                return ((ExamCrazy.Masters.Engineering_Bachelor_links)(base.Master));
            }
        }
    }
}
