//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Engineering.Electronics_Communication {
    
    
    public partial class Faraday_Law_of_Induction_Lenzs {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.EMLinks Master {
            get {
                return ((ExamCrazy.Masters.EMLinks)(base.Master));
            }
        }
    }
}
