//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.Engineering.BSNL_JTO {
    
    
    public partial class BSNL_JTO_Syllabus_Electrical {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.JTOLinks Master {
            get {
                return ((ExamCrazy.Masters.JTOLinks)(base.Master));
            }
        }
    }
}
