//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.NTSS_NTSE {
    
    
    public partial class important_dates_ntse {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.NTSE_NTSSLinks Master {
            get {
                return ((ExamCrazy.Masters.NTSE_NTSSLinks)(base.Master));
            }
        }
    }
}
