<%@ Page Language="C#" MasterPageFile="~/Masters/drdolinks.master" AutoEventWireup="True" CodeBehind="Syllabus-for-Metallurgical-Engineering-DRDO-SET.aspx.cs"  Inherits="ExamCrazy.Engineering.DRDO_SET.Syllabus_for_Metallurgical_Engineering_DRDO_SET" %>
<%@ MasterType VirtualPath="~/Masters/drdolinks.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToBreadCrum" runat="server"></asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">
<div class="gbody txt">

 

	Syllabus for Metallurgical Engineering paper DRDO-SET 
	<br><b>Thermodynamics and Rate Processes: </b>Laws of thermodynamics, activity, equilibrium constant, applications to metallurgical systems, solutions, phase equilibria, Ellingham and phase stability diagrams, thermodynamics of surfaces, interfaces and defects, adsorption and segregation; basic kinetic laws, order of reactions, rate constants and rate limiting steps; principles of electro chemistry- single electrode potential, electro-chemical cells and polarizations, aqueous corrosion and protection of metals, oxidation and high temperature corrosion - characterization and control; heat transfer - conduction, convection and heat transfer coefficient relations, radiation, mass transfer - diffusion and Fick's laws, mass transfer coefficients; momentum transfer – concepts of viscosity, shell balances, Bernoulli's equation, friction factors. 
<br>
<br><b>Extractive Metallurgy: </b>Minerals of economic importance, comminution techniques, size classification, Flotation, gravity and other methods of mineral processing; agglomeration, pyro- hydro- and electro-metallurgical processes; material and energy balances; principles and processes for the extraction of non-ferrous metals - aluminium, copper, zinc, lead, magnesium, nickel, titanium and other rare metals; iron and steel making - principles, role structure and properties of slags, metallurgical coke, blast furnace, direct reduction processes, primary and secondary steel making, ladle metallurgy operations including deoxidation, desulphurization, sulphide shape control, inert gas rinsing and vacuum reactors; secondary refining processes including AOD, VAD, VOD, VAR and ESR; ingot and continuous casting; stainless steel making, furnaces and refractories. 
<br>
<br><b>Physical Metallurgy: </b>Crystal structure and bonding characteristics of metals, alloys, ceramics and polymers, structure of surfaces and interfaces, nano-crystalline and amorphous structures; solid solutions; solidification; phase transformation and binary phase diagrams; principles of heat treatment of steels, cast iron and aluminum alloys; surface treatments; recovery, recrystallization and grain growth; industrially important ferrous and non-ferrous alloys; elements of X-ray and electron diffraction; principles of scanning and transmission electron microscopy; industrial ceramics, polymers and composites; electronic basis of thermal, optical, electrical and magnetic properties of materials; electronic and opto-electronic materials. 
<br>
<br><b>Mechanical Metallurgy: </b>Elasticity, yield criteria and plasticity; defects in crystals; elements of dislocation theory - types of dislocations, slip and twinning, source and multiplication of dislocations, stress fields around dislocations, partial dislocations, dislocation interactions and reactions; strengthening mechanisms; tensile, fatigue and creep behaviour; super-plasticity; fracture - Griffith theory, basic concepts of linear elastic and elasto-plastic fracture mechanics, ductile to brittle transition, fracture toughness; failure analysis; mechanical testing - tension, compression, torsion, hardness, impact, creep, fatigue, fracture toughness and formability. 
<br>
<br><b>Manufacturing Processes: </b>Metal casting - patterns and moulds including mould design involving feeding, gating and risering, melting, casting practices in sand casting, permanent mould casting, investment casting and shell moulding, casting defects and repair; hot, warm and cold working of metals, Metal forming - fundamentals of metal forming processes of rolling, forging, extrusion, wire drawing and sheet metal forming, defects in forming; Metal joining - soldering, brazing and welding, common welding processes of shielded metal arc welding, gas metal arc welding, gas tungsten arc welding and submerged arc welding; welding metallurgy, problems associated with welding of steels and aluminium alloys, defects in welded joints; powder metallurgy; NDT using dye-penetrant, ultrasonic, radiography, eddy current, acoustic emission and magnetic particle methods. 
	</div>
</asp:Content>
