//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamCrazy.cbse {
    
    
    public partial class cbse_10th_secondary_attendance_requirement_regular_students_admission {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ExamCrazy.Masters.CBSELinks Master {
            get {
                return ((ExamCrazy.Masters.CBSELinks)(base.Master));
            }
        }
    }
}
