<%@ Page Language="C#" MasterPageFile="~/Masters/expertspeaklinks.master" AutoEventWireup="True" CodeBehind="Career_Opportunities_in_Multimedia_Networking.aspx.cs"  Inherits="ExamCrazy.Expert_speak.Career_Opportunities_in_Multimedia_Networking" %>
<%@ MasterType VirtualPath="~/Masters/expertspeaklinks.master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToBreadCrum" runat="server"></asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">
<div class="gbody txt">

 

<table border="0" width="99%" cellspacing=2 cellpadding=2 bordercolor='#e4e4e4'>

    <tr>

      
      <td class="txt">
	<b>Career Opportunities in Multimedia &amp; Networking</b><b>
<br>Dr. </b><b>Dharm</b><b> </b><b>Bir</b><b> Singh, Director (Management Studies), NIET, Greater </b><b>Noida</b><b>, Uttar Pradesh </b></td>
</tr>

    <tr>

      
      <td class="txt">
<br>
<br><b>Market Potential in India</b>
<br><i>It is boom time again for the Indian IT training industry! The market surveys reveal an increase in technical manpower requirements--thanks to galloping offshore activities, investment in the IT infrastructure and expansion of some of the major IT companies. </i>
<br>
<br>Recent indications have shown that there has been an upward trend to reverse the market forecasts and bring fortune to the IT training institutes in India. Not only is there an increase in job requirements, but also the magnetic effect is back, especially in areas like Hardware, Networking and IT Enabled Services. The multimedia and IT industry which are closely related have expanded multifold in the past few years. Their main segments can be further divided into entertainment, publishing, networking and ITES industries. The electronic revolution symbolized by Information Technology, Telecommunication and Computers has tremendously boosted the requirements of networking professionals, multimedia content production and innovative applications. It has further expanded through powerful dissemination networks like Cable TV, Internet, Broadband and now Wireless Handheld Devices like Mobile Phones and Pocket PCs. 
<br>
<br><b>Entertainment &amp; IT Industry</b>
<br>Indian entertainment industry is estimated to be $4 billion (around Rs. 17,200 Crores) in 2007 with the current growth rate of 20% per annum. The IT Enabled Services (ITES) sector, which includes interactive/digital multimedia, animation and gaming, is expected to employ around 1.1 million professionals by year 2008. Computer, Video and Wireless (Mobile) Game development is also showing a very promising growth, wherein 80% of the projects are outsourced from the western countries to India. The animation industry, which is growing at the rate of 30% every year, is expected to be around $1 billion as per the NASSCOM reports. Around 80 to 100 million TV homes, hundreds of TV channels in variety of regional languages, over 60000 Cable Operators in India, are increasingly demanding for media content to provide 24x7 entertainment and information services for the television viewers. Also the Internet and Broadband subscribers are expected to grow to the extent of 40 million and 20 million respectively in India by year 2008. The essence of these indicators is that there is very bright future for the multimedia industry. India can achieve the future market projections only if it develops strong multimedia training and education culture. 
<br>
<br>According to NASSCOM Research on the skill set requirements, as the Indian companies move up the value chain to achieve the US$ 50 billion export target by year 2008, the skills set requirements would be across high growth potential verticals. At the same time, the industry will also need to equip itself with the domain expertise across each of these verticals to service the high-end work coming to India. Growth in this sector would come from more specialized courses tailor-made specifically for niche industries. The fact is that as far as software is concerned, India is a back-bencher that happily develops backend codes while blissfully ignoring product development. But this may not hold true for multimedia, where the country can successfully productize its creative prowess for international markets. India has developed and honed its artistic skills in architecture, painting, theatre, music and prose for thousands of years. Indians also have an excellent understanding of English and international culture while maintaining their own strong identities. 
<br>
<br><b>Skills in demand </b>
<br>Around five years ago, it was Java, XML, Wireless, eSecurity, .Net, Supply Chain Management, CRM, and ITES, which were hot. This year the focus is on UNIX, Linux, .NET and CCNA. 
<br>
<br>In the high-end training segment, there are three areas that will stand out. These are database management system, security and networking on new platforms. In terms of networking, there will be a shortage of 1 million networking professionals by 2009, as per an IDC research. The Asia-Pacific skills gap is expected to increase at a rate of 41 percent, resulting in a shortage of almost 1,37,200 networking professionals by 2009. In the field of Networking, international certification like Cisco Certified Network Associate (CCNA) is in very high demand. Added to this, employers also opt for other vendor certified courses. 
<br>
<br>The skills sets that are going to drive the IT training market are the requirements for networking and system administration professionals, e-security solution implementation experts, auditors and cyber crime investigation professionals. In addition, embedded systems programmers and designers, .Net, XML and Java professionals with wireless and mobile applications expertise are also going to be the most sought after. Even the NASSCOM survey predicts that skills that would be in demand would be for software analysts, domain specialists, information security, integration specialists, database administrators and network specialists. IT professionals need to train themselves in areas like document management applications, middleware applications, process modeling, etc. These are the areas that are expected to create opportunities in the future 
<br>
<br>Experts point out that certifications, which are going to be in vogue in the future, are Microsoft, Oracle, Sun, RedHat (Linux) and Cisco. However, it would be networking certifications, which would be in more demand than ever. 
<br>
<br><b>Trends in Multimedia and Networking Education</b>
<br>‘Multimedia Professionals' the term, which is often used by the multimedia training institutes to address those persons who use multimedia for developing a variety of applications. However the term ‘multimedia professional' is very general and it can encompass all the creative and non-creative activities. Therefore, we are restricting ourselves to the education of ‘multimedia-application-developers' (those involved in visualization, design and development). There is another important category, which can be referred as ‘multimedia-technology-developers'. This one needs far greater support and boost as compared to the education of multimedia-application-developers. 
<br>
<br>Many view computer networking as one of the best and "hottest" career fields available today. Some claim that a serious shortage of qualified people to fill these networking jobs exists, and these claims may lure some people into the fray hoping for an easy position with a fast-growing company. Debates over the actual extent of any "shortages" aside, networking involves mostly hard work, and competition for the high-quality positions will always be strong. 
<br>
<br><b>Job Titles in Networking</b>
<br>Several types of positions exist in networking, each with different average salaries and long-term potential, and one should possess a clear understanding of these. Unfortunately, job titles in networking and in Information Technology (IT) generally, often lead to confusion among beginners and experienced folks alike. Bland, vague or overly bombastic titles often fail to describe the actual work assignments of a person in this field. The basic job titles one sees for computer networking and networking-related positions include 
	<br>Network Administrator 
	<br>Network (Systems) Engineer 
	<br>Network (Service) Technician 
	<br>Network Programmer/Analyst 
	<br>Network/Information Systems Manager 
	<br><b>The Network Administrator</b>
<br>In general, network administrators configure and manage LANs and sometimes WANs. The job descriptions for administrators can be detailed and sometimes downright intimidating! <b>Network Administrators</b> are responsible for analysis, installation and configuration of company networks. Their daily activities include monitoring network performance, troubleshooting problems and maintaining network security. Other activities may include assisting customers with operating systems and network adapters, configuring routers, switches, and firewalls, and evaluating third-party tools. 
<br>Needless to say, a person early in their career often lacks experience in a majority of these categories. Most employers do not expect candidates to possess in-depth knowledge of all above-mentioned areas 
<br>
<br><b>Comparing Roles and Responsibilities in Networking </b>
<br>The job function of a <b>Network Engineer</b> differs little from that of a Network Administrator. Company A may use one title while Company B uses the other to refer to essentially the same position. Some companies even use the two titles interchangeably. Firms making a distinction between the two often stipulate that administrators focus on the day-to-day management of networks, whereas network engineers focus primarily on system upgrades, evaluating vendor products, security testing, and so on. 
<br>
<br>A <b>Network Technician</b> tends to focus more on the setup, troubleshooting, and repair of specific hardware and software products. Service Technicians in particular often must travel to remote customer sites to perform "field" upgrades and support. Again, though, some firms blur the line between technicians and engineers or administrators. 
<br>
<br><b>Network Programmer/Analysts</b> generally write software programs or scripts that aid in network analysis, such as diagnostics or monitoring utilities. They also specialize in evaluating third-party products and integrating new software technologies into an existing network environment or to build a new environment. 
<br>
<br><b>Systems Managers</b> supervise the work of administrators, engineers, technicians, and/or programmers. Network / Information Systems Managers also focus on longer-range planning and strategy considerations. Salaries for networking positions depend on many factors such as the hiring organization, local market conditions, a person's experience and skill level, and so on. 
<br>
<br><b>Training Options in Multimedia &amp; Networking</b>
<br>Multimedia training in India is mainly imparted through various institutes across the country. The training syllabus offered by many institutes revolves around teaching and promotion of branded software products. Hence, there is less emphasis on conceptualization and visualization of innovative multimedia applications. There has to be strong emphasis on conceptualization and realization of various applications. Also the ancillary subjects like interaction and interface design, visual communication, content structuring, user experience design, interactive storytelling, script writing, and several other related topics should be very well covered. Problem solving multimedia-application-developers can be produced only if adequate emphasis is given on ancillary subjects apart from the usage of regular software and hardware tools. Like a typical wave graph, the initial rise in multimedia training was driven by the quantity of students trained. This wave is now declining as the market is maturing. The next rise of this wave demands multimedia education, which is deeply grounded in academic content. The industry is just beginning to understand the different streams of specializations like 2D animation, 3D animation, special effects, multimedia scripting/programming, non-linear video editing, instruction design, interaction design, content structuring, content management, and so on. Application oriented specializations are yet to reflect in the academic curriculums e.g., 3D modeling for games requires different set of skills than the 3D modeling for video production. 
<br>
<br>Network administrators and managers in particular have grown fond of networking-based certifications like Microsoft MCSE and Cisco CCNA. In general, to gain and keep a certification one must pass a lengthy (usually multiple-choice question) paper exam, then pass recertification exams at periodic intervals (usually every two or three years). A person has the choice of preparing for the exam through self-study or by enrolling in a certification course or "program" run by a training organization (in case of Cisco it is Cisco Local Academy). Certifications are designed to accredit someone for a certain amount of industry experience that they've already gained. Some of the programs will even make recommendations to this effect, typically one to two years of prior background for the entry-level certifications. However, experience is not strictly required. Some have criticized the entry-level exams for being too "bookish" in this respect, too easy to pass without prior hands-on experience. Which certification is best? MCSE? CCNA? Something else? Again, the answer depends on the individual's interests and also the preferences of hiring companies. 
<br>
<br><b>Weaknesses in the Pedagogy and Requirements of Employers</b>
<br>Traditionally, the multimedia training industry in general is focused more on the creative side of a person; which in turn is aimed at bringing out latent talent and transforming it to perceptible reality. However, the multimedia industry insists that course curriculums should include fundamentals of animation, design aesthetics, story narration, performance skills, timing and staging. The professional programmes should also deal with subjects related to art direction, scripting, art of animation and a good amount of real project experience. On the whole, there should be harmony between technology and creativity. Thus we can say that present multimedia education lacks pedagogical maturity. Some multimedia courses are highly tool oriented wherein the focus is on teaching the user interface of branded software products. Some of them have a mixture of diverse topics with very superficial coverage. The specialization based multimedia courses are very rare. The approach should be to provide a good blend of theory with practice so that the student may learn the concepts in a better way. The multibillion dollar IT industry of India is thriving on thousands of software professionals which have been produced through such training programs only. With China providing a competitive alternative to offshore IT projects, it is paramount for us to elevate the level of IT training and education. Employers of multimedia-application-developers are demanding for specialization during the recruitment. Also there is a need to clearly understand different roles and related skill sets within the multimedia domain. Generally, the emphasis on technical capability is much higher than the design and visualization skills. Ideally, it should be on both. The employers expect both types of capabilities from the same person to save costs. It is unfair to expect a visualizer to be good at lingo-scripting and vise versa. This results in mediocre quality of multimedia applications. 
<br>
<br>Many companies, particularly larger ones, offer their employees ongoing training opportunities in Networking. The employer will either build their own courses or will bring in an outside company to hold the training. These courses are typically focused on a specific product technology or tool, or on the specific technical information needed to pass a certification exam. One could argue it is preferable for the beginning networker to focus on general technologies at first rather than certifications, as companies in these cases prefer to train employees "their own way" anyhow. Cisco being the global market leader is the preferred choice among the learners and the companies as well. 
<br>
<br><b>The Future </b>
<br>If the Indian film industry can produce largest number of films in the entire world then why can't multimedia industry produce the largest number of CD Titles or Games or multimedia applications or websites? This can definitely happen if the domestic use of multimedia increases. If India can produce the most talented software engineers then why can't it produce the most creative multimedia- developers? If a country like Malaysia which is smaller than Mumbai city, can establish a Multimedia University, why shouldn't we expect much more from India? There is a tremendous potential for multimedia industry to grow. Government of India may use multimedia as an effective tool to promote culture, tourism, education and rural development at a very large scale to create the desired impact. There are problems that multimedia can solve and there is this hugely talented Indian youth waiting for the opportunity. All we need is the support, good environment and high quality multimedia education to hone skills at an affordable fee. 
<br>
<br>Some people have asserted that networking (and IT generally) is a "young person's game," and that companies generally prefer to turn over their employee base periodically, to bring in younger, more affordable workers. This concept might sound appealing to some, but if it were true, it would make networking careers less inviting to most people. Realistically, the field of computer networking presents so much complexity, and involves such a wide range of technologies, that most serious companies should value both experienced employees and ambitious new employees highly. In fact, an effective career strategy involves seeking out more experienced people in one's field, and learning new skills from these mentors. 
<br>
<br>Many firms view four-year degrees as a sign of commitment to the field. Network technology changes very fast, so employers care both about a person's current knowledge and also their ability to learn and adapt for the future. Certifications effectively prove current knowledge, but college degrees best demonstrate one's general learning ability. Self-study in networking is always effective and underrated by many. By making contacts with those in networking careers, either people in one's local area, or individuals or sites on the Internet, one can quickly acquire a wealth of information ranging from technical details, to advice on writing a resume, to advice on specific hiring companies, schools, and so on. 
</td>
</tr></table>
</div>
</asp:Content>
